config/routes.rb
Rails.application.routes.draw do
 
  

  root 'blogs#index'

  mount RailsAdmin::Engine => '/administrador', as: 'rails_admin'
  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base

	validates :email, presence: true
	validates :name, presence: true
	validates :gift, presence: true
	validates :rima, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @blog = Blog.new
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'La información del jugador fue guardada con exito. ' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'La información del jugador fue actualizada con exito. ' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:email, :name, :gift, :rima)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Regalo %><br>
    <%= f.text_area :gift %>
  </div>
  <div class="field">
    <%= f.label :rima %><br>
    <%= f.text_area :rima %>
  </div>
  <div class="actions">
    <%= f.submit "Inscribir amigo secreto" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editar Amigo Secreto</h1>

<%= render 'form' %>

<%= link_to 'Ver', @blog %> |
<%= link_to 'Atras', blogs_path %>

app/views/blogs/index.html.erb
    
        <ul class="cb-slideshow">
            <li><span <%= image_tag("feliz.mp3") %>>Image 01</span><div><h3>Feliz·Navidad</h3></div></li>
            

            <li><span>Image 02</span><div><h3>Feliz·Navidad</h3></div></li>
            <li><span>Image 03</span><div><h3>Feliz·Navidad</h3></div></li>
            <li><span>Image 04</span><div><h3>Prospero Año</h3></div></li>
            <li><span>Image 05</span><div><h3>Y Felicidad</h3></div></li>
            <li><span>Image 06</span><div><h3>Primates Chilpayates</h3></div></li>
        </ul>

            <div id="contenido">
              
              <h1 class="white center"> Feliz Navidad  Familia :) </h1>

              <p class="para">Para inscribirse al Amigo secreto de este año por favor
                 presionar el botón instrucciones, una vez hayan leido 
                 las instrucciones presionar el botón Jugar.  
              </p>  

              <div class="buton">
                <button type="button" class="instrucciones create-btn btn-large" data-toggle="modal" data-target="#instrucciones">
                Instrucciones
                </button>
              
                <button type="button" class="instrucciones create-btn btn-large" data-toggle="modal" data-target="#mynewplayer">
                Jugar
                </button>
              </div>

            </div>
            
            <audio autoplay="autoplay" loop="loop"><source src="/assets/feliz-5a49821d52f6111c6cbe5ad5f49da4b074b2cc6964aa961c2efb328565a2a033.mp3" type="audio/mpeg" /></audio>
        



          <!-- Instruciones -->

          <div class="modal fade" id="instrucciones" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">

                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class=" center modal-title" id="myModalLabel">Instrucciones</h4>
                  </div>
                    <p>
                      <br>
                      Querida Familia, este año volveremos a jugar al amigo secreto. Para facilitar la dinámica del juego he creado esta aplicación web, que se encargara de todo el trabajo de receptar, organizar y sortear a los jugadores. Esta aplicación dará a conocer las reglas del juego a todos los integrantes de la familia. Mi asistente personal “Femputadora” que fue construida con este único propósito, será la encargada de sortear a los jugadores, por lo tanto no existe ningún tipo de preferencia, trampa o error humano en el proceso.
                      <br>
                      <br>
                      Su única misión consiste en leer y entender las reglas del juego, una vez que estas estén claras, podrán oprimir el botón “Jugar” al final de esta pagina.
                      <br>
                      <br>
                      1-  Todos los participante deberán estar registrados hasta el MIERCOLES 9 DE DICIEMBRE. 
                      <br> 
                      <br>
                      2-  El precio máximo del regalo que pueden pedir será de 50 usd.
                      <br>
                      <br>
                      3-  Cada Jugador deberá pensar en el regalo que más quiera recibir en este año. El regalo debe ser 
                      algo posible de comprar dentro del tiempo, espacio y presupuesto en los que se desarrolla este juego.
                      <br>
                      <br>
                      4-  Una vez que cada jugador tenga definido su regalo deberán utilizar su infinita imaginación y alma poética para escribir:
                      <blockquote> 
                        Un poema brillante octosílabos preciso ,que en el final finaliza
                        y empieza por adelante.
                        Debe tener ocho versos
                        y ser de rima elegante. 
                      </blockquote>
                      <br>
                      5-  El punto cuatro puede ser ignorado. Pero de todas formas deberán describir su regalo deseado en forma de rima. La rima deberá dar una pista del regalo deseado y la persona que lo vaya a recibir. Pueden tomar como ejemplo esta pésima rima:
                      <br>
                      <br>
                      Rima:
                      <blockquote>Este curioso personaje,
                      Un 29 de febrero nace,
                      Y en esta navidad solo desea,
                      Que sus pies cubiertos sean.
                      </blockquote>
                              Personaje: Henry Sebastián.
                              <br>
                              Regalo: Zapatos.
                      <br>
                      <br>
                      6-  El poema con la mejor rima se llevara el regalo secreto de este año.
                      <br>
                      <br>
                      7-  En contraste el dueño de la rima menos elaborada, será el encargado de organizar el amigo secreto del siguiente año.
                      <br>
                      <br>
                      8-  Una vez tengan todo esto claro, podrán presionar el botón “Jugar”; y llenar el formulario con la siguiente información: 
                      <ul>  
                      <li> a.  Email del representante </li>
                      <li> b.  Nombre del Jugador </li>
                      <li> c.  Regado Elegido y descripción del mismo. </li>
                      <li> d.  Rima </li>
                      </ul>
                      <br>
                      <br>
                      9-  Si el regalo es algo difícil de encontrar puede agregar a la descripción un lugar de donde comprarlo o cualquier otra consideración en el espacio destinado para descripción del regalo. 
                      <br>
                      <br>
                      <h1 class="center">IMPORTANTE INFORMACIÓN PARA LLENAR EL FORMULARIO</h1>
                      <br>
                      A.  Cada jugador esta encargado de realizar su rima. Sin embargo, un jugador puede escoger un representante para enviar la información de su regalo y su rima.  
                      <br>
                      <br>
                      B.  Una persona puede representar a un grupo entero de jugadores. Por ejemplo yo: “Henry Sebastián” representaré a mi papa, mama y hermana Josy.
                      <br>
                      <br>
                      C.  El representante del grupo deberá llenar el formulario para cada jugador y DEBERÁ UTILIZAR SU CORREO ELECTRONICO, como forma de comunicación. Como ejemplo: Yo “Henry Sebastián” llenare el formulario 4 veces incluyendo mi información, la de papá, mamá y hermana, pero en todos los formularios utilizare mi correo electrónico.
                      <br>
                      <br>
                      D.  Una vez que haya recibido toda la información. “Femputadora” realizara el trabajo para la cual fue creada. 
                      <br>
                      <br>
                      E.  El representante del grupo recibirá la información del amigo secreto de todos los jugadores y será el encargado de transmitir esa información a su grupo y/o/U familia. 
                      <br>
                      <br>
                      F.  En caso de alguna duda, aclaración, sugerencia, o si no logran descubrir el regalado podrán escribirme de manera directa a henry2992@hotmail.com. Sin embargo, el jugador que pida “ayuda fuera de la normal” quedará descalificado para el premio final.
                      <br>
                      *Considérese como “ayuda fuera de lo normal”, al pedido explicito de revelar un nombre o premio.
                      <br>
                      <br>
                      G.  Los jugadores recibirán la información de su amigo secreto el día Domingo 13 de Diciembre. 

                      </p>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">Cerrar y Jugar al Amigo Secreto :)</button>
                  </div>
                </div>
              </div>
            </div>

        



 <!-- Modal  create action -->
      <%= form_for(@blog) do |f| %>
        <div class="modal fade" id="mynewplayer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">

            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class=" center modal-title" id="myModalLabel">Jugar al amigo Secreto :)</h4>
            </div>
            
               <div class="field center">
                <%= f.label :Email  %><br>
                <%= f.text_field :email, class: "form-control post_content" %>
              </div>
              <div class="field center">
                <%= f.label :Nombre %><br>
                <%= f.text_field :name, class: "form-control post_content" %>
              </div>
              <div class="field center">
                <%= f.label :Regalo %><br>
                <%= f.text_area :gift,class: "form-control post_content" %>
              </div>
              <div class="field center">
                <%= f.label :Rima %><br>
                <%= f.text_area :rima, class: "form-control post_content" %>
              </div>
            

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">Cerrar</button>
              <%= submit_tag "Inscribir", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
        </div>
      <% end %>
    <!-- Modal -->

app/views/blogs/new.html.erb
<h1>Crear Nuevo Amigo Secreto :)</h1>

<%= render 'form' %>

<%= link_to 'Atras', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @blog.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @blog.name %>
</p>

<p>
  <strong>Regalo:</strong>
  <%= @blog.gift %>
</p>

<p>
  <strong>Rima:</strong>
  <%= @blog.rima %>
</p>

<%= link_to 'Editar', edit_blog_path(@blog) %> |
<%= link_to 'Atras', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrimatesChilpayates</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

   <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
</head>
<body id="page">

<%= yield %>

</body>
</html>